### ISSUE TITLE
support phpstorm etc?

### ISSUE THREAD

**Issue by kehh** [MichaelSnowden/intellij-gas-plugin#1]
I'm interested in this plugin - just wondering if you contemplated supportign PHPStorm / WebStorm / PhCharm?

**Comment by MichaelSnowden** [comment]
I haven't considered it, u fortunately.

On Monday, November 16, 2015, Kehan Harman <notifications@github.com> wrote:

> I'm interested in this plugin - just wondering if you contemplated
> supportign PHPStorm / WebStorm / PhCharm?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MichaelSnowden/intellij-gas-plugin/issues/1>.
>


-- 
Michael

**Comment by kehh** [comment]
looks like it's pretty straightforward: http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html

**Comment by MichaelSnowden** [comment]
I'll try getting around to this over the Winter break (in 2 weeks). Thanks for the request!

**Comment by MichaelSnowden** [comment]
Very straightforward, indeed! 
```
    <!-- uncomment to enable plugin in all products
    <depends>com.intellij.modules.lang</depends>
    -->
```

**Comment by MichaelSnowden** [comment]
I'll push a change and resubmit the plugin. Will comment back here when I've confirmed that I can download it on PyCharm.

**Comment by MichaelSnowden** [comment]
https://plugins.jetbrains.com/update/index?pr=&updateId=22998
Looks to be working now. Thanks!

**Comment by kehh** [comment]
Excellent thanks
