### ISSUE TITLE
Problem with granting access to Google Drive

### ISSUE THREAD

**Issue by ntucakovic** [MichaelSnowden/intellij-gas-plugin#6]
This is the case I've got when trying to set up your plugin.

I've got project ID and I went `ctrl + shift + o` to download the project, which opened granting permissions from my google account. Problem is I've accepted it on a wrong google account, not the one where all my scripts are (had regular and incognito window open and for some reason it used account from incognito). And now there's no way to somehow break that connection between PHPStorm (any intelij similar IDE I guess) and Google.

It can't find project with the ID provided (in that account I guess) and it just fails silently.

I've tried revoking access permissions from the wrong account, hoping that it would ask again for permissions, but nothing is happening.

Any ideas on what to do?

**Comment by MichaelSnowden** [comment]
`private static final java.io.File DATA_STORE_DIR = new java.io.File(
            System.getProperty("user.home"), ".credentials/gas-plugin");`

Your credentials are stored here, so just delete this directory and you should be fine.

**Comment by ntucakovic** [comment]
Thanks! Works now :)
